spring.application.name=gateway-service
server.port=8888
spring.cloud.config.enabled=false
spring.cloud.discovery.enabled=false
# Il faut remplacer localhost par l?adresse IP où se trouve le service,
# ou par le nom du service Eureka dans docker-compose
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.instance.prefer-ip-address=true
# Spécifier le nom du microservice en minuscules
spring.cloud.gateway.discovery.locator.lower-case-service-id=true