spring.application.name=ticket-service
server.port=8083

spring.datasource.url=jdbc:postgresql://localhost:5432/ticketdb
spring.datasource.username=user
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

spring.cloud.discovery.enabled=true
spring.cloud.config.enabled=false

management.endpoints.web.exposure.include=*
# Il faut remplacer localhost par l?adresse IP où se trouve le service,
# ou par le nom du service Eureka dans docker-compose
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.instance.prefer-ip-address=true